[project]
name = "lib-version"
version = "0.0.1"
authors = [
  { name="Lucian", email="author@example.com" },
  { name="Ming_Da", email="m.d.yang@student.tudelft.nl"}
]
description = "A version aware package"
readme = "README.md"
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]


[project.urls]
Homepage = "https://github.com/Release-Engineering-4/lib-version"

[project.files]
version = {path = "version.txt"}